name: bookfair
channels:
- lenskit
- mdekstrand/label/pre
- mdekstrand
- defaults
- conda-forge  # last so it is not preferred
dependencies:
- python=3.7
- pip
- docopt
- numpy>=1.17
- pandas>=0.24
- pyarrow
- fastparquet
- lenskit=0.9
- sqlalchemy
- seaborn
- plotnine
- tqdm
- zstandard
- python-blosc
- notebook
- ipython
- ipywidgets
- nbformat
- nbconvert
- papermill
- cffi
- joblib
- postgresql>=11
- psycopg2
- scipy
- tbb
- scikit-learn
- implicit
- tzlocal
- simplegeneric
- hpfrec
- colorama
- requests
- flake8
- dvc>=0.84
- gitpython
- pydrive2
- boto3
- toml
- nbdime
- zarr
# things for stan
- cxx-compiler
- make
- ujson
- pip:
    - pystache
    - scikit-optimize
    - cmdstanpy>=0.9
    - natural
